Repository AbubakarSattar-dev/HackerRank-ProblemSolutions, pull requests merged in 2022-10, with the labels that each got.

#7 Created JavaList.java
  Java/JavaList.java
Labels: hacktoberfest-accepted

#6 Create python-loop.py
  Python/python-loop.py
Labels: hacktoberfest-accepted

#9 Create Find_string.py
  Python/Find_string.py
Labels: hacktoberfest-accepted

#4 Create Vector-Sort.cpp
  C++/Vector-Sort.cpp
Labels: hacktoberfest-accepted

#16 HackerRank Problem, Write A Function, In Python
  CONTRIBUTORS.md
  Python/4_Write_A_Function.py
Labels: hacktoberfest, hacktoberfest-accepted, code added

#15 added The-Minion-Game.py
  Python/TheMinionGame.py
Labels: hacktoberfest, hacktoberfest-accepted, code added

#13 Added Fizz Buzz Prob
  Python/fizz buzz.py
Labels: hacktoberfest, hacktoberfest-accepted, code added

#12 Dynamic Array solution
  Java/DynamicArray.java
Labels: hacktoberfest, hacktoberfest-accepted, code added

#11 Create StringStream.cpp
  C++/StringStream.cpp
Labels: hacktoberfest, hacktoberfest-accepted, code added

#39 Added C++ file
  C++/HelloWorld.cpp
  CONTRIBUTORS.md
  profiles/mahnoor26.md
Labels: hacktoberfest-accepted

#17 Create Java Substring
  Java/Java Substring
Labels: hacktoberfest, hacktoberfest-accepted

#20 sum of two numbers
  C++/sum.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#21 Create codecon.cpp
  C++/codecon.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#66 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: hacktoberfest, hacktoberfest-accepted

#44 Hello World program in python
  C++/Input_and_Output.cpp
  CONTRIBUTORS.md
  Python/Hello World.py
  profiles/Mahnoor Shoukat.md
Labels: hacktoberfest, hacktoberfest-accepted

#55 Java String Reverse solution added in java
  C++/Maps-STL.cpp
  Java/Java String Reverse.java
Labels: hacktoberfest, hacktoberfest-accepted

#40 I added a new file
  CONTRIBUTORS.md
  profiles/githubusername.md
  profiles/mahnoor26.md
Labels: hacktoberfest, hacktoberfest-accepted

#25 sum code in cpp added
  C++/code.cpp.txt
Labels: hacktoberfest, hacktoberfest-accepted

#70 Python Space management Solution added
  CONTRIBUTORS.md
  Python/TheMinionGame.py
  Python/space_management.py
Labels: hacktoberfest, hacktoberfest-accepted

#27 first Code in Python
  CONTRIBUTORS.md
  Python/1_ArithmeticOperators.py
  Python/1_WriteAFunction.py
  Python/2_FindTheRunnerUpScore.py
  Python/3_ListComprehensions.py
  Python/main.py
Labels: hacktoberfest, hacktoberfest-accepted

#74 Swap Case
  Python/5_SwapCase.py
Labels: hacktoberfest, hacktoberfest-accepted

#78 C++ code Queue with array
  C++/ImplementQueueWithArray.cpp
  C++/reverseLinkedList.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#84 Added HashSet in Java
  Java/Java_HashSet.java
Labels: hacktoberfest, hacktoberfest-accepted

#87 Create Aznaijaz.md
  profiles/Aznaijaz.md
Labels: hacktoberfest, hacktoberfest-accepted

#86 Add files via upload
  B_24684.ipynb
Labels: hacktoberfest, hacktoberfest-accepted

#106 Exception Handling
  Python/6_Exceptions.py
Labels: hacktoberfest, hacktoberfest-accepted

#102 I added a new project
  CONTRIBUTORS.md
  Python/pingPong/ball.py
  Python/pingPong/main.py
  Python/pingPong/paddle.py
  Python/pingPong/scoreboard.py
  Python/snakeGame/food.py
  Python/snakeGame/main.py
  Python/snakeGame/scoreboard.py
  Python/snakeGame/snake.py
  profiles/Zain Ali Shah.md
Labels: hacktoberfest, hacktoberfest-accepted

#93 Create hajra.ipynb
  Python/hajra.ipynb
Labels: hacktoberfest, hacktoberfest-accepted

#98 Create hajra6.md
  profiles/hajra6.md
Labels: hacktoberfest, hacktoberfest-accepted
